### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Reza-CyBer44/Fivem-Discord-Control#1]
SCRIPT ERROR: citizen:/scripting/lua/json.lua:397: bad argument #1 to 'strfind' (string expected, got nil)
> fn (@DiscordComm/Server.lua:215)

**Comment by Reza-CyBer44** [comment]
Make Sure you Entered Correct Channel id in Config file.

**Comment by ghost** [comment]
My own fault sorry. Didn't understand how to do permissions with the bot, googled it and got there in the end.
